### ISSUE TITLE
nil is not a valid `source` parameter for remote_file

### ISSUE THREAD

**Issue by docwhat** [chef-cookbooks/wix#9]
### Cookbook version
WIX v2.0.2

### Chef-client version
12.12.15

### Platform Details
Windows 2012 R2 Standard

### Problem:

```
Chef::Exceptions::InvalidRemoteFileURI: nil is not a valid `source` parameter for remote_file. `source` must be an absolute URI or an array of URIs.
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/resource/remote_file.rb:143:in `block in validate_source'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/resource/remote_file.rb:141:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/resource/remote_file.rb:141:in `validate_source'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/mixin/params_validate.rb:317:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/mixin/params_validate.rb:317:in `block in _pv_callbacks'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/mixin/params_validate.rb:316:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/mixin/params_validate.rb:316:in `_pv_callbacks'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/mixin/params_validate.rb:106:in `block (2 levels) in validate'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/mixin/params_validate.rb:103:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/mixin/params_validate.rb:103:in `block in validate'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/mixin/params_validate.rb:93:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/mixin/params_validate.rb:93:in `validate'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/property.rb:470:in `validate'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/property.rb:660:in `coerce_and_validate'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/property.rb:639:in `input_to_stored_value'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/property.rb:392:in `set'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/property.rb:291:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/mixin/params_validate.rb:483:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/mixin/params_validate.rb:122:in `set_or_return'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/resource/remote_file.rb:51:in `source'
C:/chef/cache/cookbooks/wix/recipes/default.rb:25:in `block in from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/resource_builder.rb:76:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/resource_builder.rb:76:in `build'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/dsl/declare_resource.rb:277:in `build_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/dsl/declare_resource.rb:234:in `declare_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/dsl/resources.rb:40:in `remote_file'
C:/chef/cache/cookbooks/wix/recipes/default.rb:24:in `from_file'
...
```

Sometimes [`CodePlex.download_url()`](https://github.com/chef-cookbooks/wix/blob/v2.0.2/recipes/default.rb#L21) returns `nil` ... 

I'm not sure what to do... 

* Cache the previous value and use that if available?
* Just skip the rest of the recipe?
* Throw a better error?

My windows systems run every 30 minutes and I get this about 3-5 times a day per system.

It's possible we're being throttled?  I don't think it is a network problem, unless it is at CodePlex's side.

Since several of our boxes use this, being able to specify the `download_url` via an attribute and letting us cache it would be handy.  I could even use the `CodePlex.download_url()` to automate the caching.

**Comment by docwhat** [comment]
This is still a problem in v3.0.0 of the cookbook.
